spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          enabled: true
      routes:
        - id: activity-route
          uri: lb://activity
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1
domain: config-server
