spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          enabled: true
      routes:
        - id: config-client
          uri: lb://config-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
domain: config-server
