spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          enabled: true
      routes:
        - id: config-client
          uri: lb://config-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
domain: config-server
