server:
  port: 8765
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          enabled: true
      routes:
        # This route rule used to forward request to activity server
        - id: activity-route
          uri: lb://activity
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/